DROP TRIGGER IF EXISTS TI_M59PRE2 ON M59PRE2 CASCADE  ; 
DROP TRIGGER IF EXISTS TD_M59PRE2 ON M59PRE2 CASCADE  ; 
DROP FUNCTION IF EXISTS  FTA_M59PRE2 () CASCADE; 


CREATE OR REPLACE FUNCTION FTA_M59PRE2() RETURNS TRIGGER AS $$
    BEGIN
	IF (TG_OP = 'INSERT') THEN
		UPDATE M57PREH M57U
		SET Recs2=COALESCE(M59.DTL,0)
		FROM 
		(
		SELECT M57.KdJAsu,M57.lvlbenefit,COUNT(M59.KdJAsu) AS DTL
		FROM M57PREH M57
		LEFT JOIN M59PRE2 M59
		ON M59.KdJAsu=M57.KdJAsu and M59.LvlBenefit = M57.LvlBenefit 
		WHERE NEW.KdJAsu=M57.KdJAsu AND
		      NEW.LvlBenefit=M57.LvlBenefit	
		GROUP BY M57.KdJAsu,M57.lvlbenefit		
		) M59
		--
		WHERE M59.KdJAsu=M57U.KdJAsu and M59.LvlBenefit = M57U.LvlBenefit; 

		IF NOT FOUND THEN RETURN NULL; END IF;

		RETURN NEW;		      
	END IF; 
	
	IF (TG_OP = 'DELETE') THEN
		UPDATE M57PREH M57U
		SET Recs2=COALESCE(M59.DTL,0)
		FROM 
		(
		SELECT M57.KdJAsu,M57.lvlbenefit,COUNT(M59.KdJAsu) AS DTL
		FROM M57PREH M57
		LEFT JOIN M59PRE2 M59
		ON M59.KdJAsu=M57.KdJAsu and M59.LvlBenefit = M57.LvlBenefit 
		WHERE OLD.KdJAsu=M57.KdJAsu AND
		      OLD.LvlBenefit=M57.LvlBenefit	
		GROUP BY M57.KdJAsu,M57.lvlbenefit		
		) M59
		--
		WHERE M59.KdJAsu=M57U.KdJAsu and M59.LvlBenefit = M57U.LvlBenefit; 
		      
		IF NOT FOUND THEN RETURN NULL; END IF;

		RETURN OLD;		      
	END IF; 	
    END;	
$$ LANGUAGE plpgsql;

/******
TRIGGER 
*******/
CREATE TRIGGER TI_M59PRE2
AFTER INSERT ON M59PRE2
    FOR EACH ROW EXECUTE PROCEDURE FTA_M59PRE2();
------
CREATE TRIGGER TD_M59PRE2
AFTER DELETE ON M59PRE2
    FOR EACH ROW EXECUTE PROCEDURE FTA_M59PRE2();    
    

