DROP FUNCTION IF EXISTS  FTA_M05DJAB () CASCADE; 

DROP TRIGGER IF EXISTS TI_M05DJAB ON M05DJAB CASCADE  ; 
DROP TRIGGER IF EXISTS TD_M05DJAB ON M05DJAB CASCADE  ; 

--
CREATE OR REPLACE FUNCTION FTA_M05DJAB() RETURNS TRIGGER 
AS $$
    BEGIN
	UPDATE M04HJAB
	SET Recs=COALESCE(M05.DTL,0)
	FROM
	(
	SELECT Kode,DTL=COUNT(Kode)
	FROM M05DJAB
	GROUP BY Kode
	) M05
	--
	INNER JOIN M04HJAB M04
	ON M04.Kode=M05.Kode
	WHERE M04.Kode=l_Kode; 
	--
        IF (TG_OP = 'DELETE') THEN
            RETURN OLD;

        ELSIF (TG_OP = 'INSERT') THEN
            RETURN NEW;
            
--        ELSIF (TG_OP = 'UPDATE') THEN
--            RETURN NEW;
        END IF;
    END;
$$ language 'plpgsqlo' ;  

--
CREATE TRIGGER TI_M05DJAB
AFTER INSERT ON M05DJAB
    FOR EACH ROW EXECUTE PROCEDURE FTA_M05DJAB();
--
CREATE TRIGGER TD_M05DJAB
AFTER DELETE ON M05DJAB
    FOR EACH ROW EXECUTE PROCEDURE FTA_M05DJAB();
