DROP TRIGGER IF EXISTS TD_M15PEGA ON M15PEGA CASCADE  ; 
DROP FUNCTION IF EXISTS  FTA_M15PEGA () CASCADE; 

CREATE OR REPLACE FUNCTION FTA_M15PEGA() RETURNS TRIGGER AS $$
    BEGIN

	DELETE FROM S08MUTA
	WHERE NIP=OLD.NIP; 
	IF NOT FOUND THEN RETURN NULL; END IF;

	RETURN OLD;
    END;	
$$ LANGUAGE plpgsql;

---------------------
-- Trigger Delete
CREATE TRIGGER TD_M15PEGA
AFTER DELETE ON M15PEGA
    FOR EACH ROW EXECUTE PROCEDURE FTA_M15PEGA();
-- End Trigger 


