
CREATE OR REPLACE FUNCTION public.p_create_temp1 (in l_tmpcode varchar, out l_created int4) RETURNS int4 AS
$BODY$
--LOOK UP KE TABLETEMP, CARI DEFINISI KOLOM YANG AKAN DI-CREATE
DECLARE l_SQLSTATE  VARCHAR(8000);
DECLARE l_TBLSTRUC  VARCHAR(5000);
BEGIN 
IF EXISTS (SELECT TMPCODE FROM TABELTEMP WHERE TMPCODE = l_TMPCODE) THEN 
   BEGIN
     l_TBLSTRUC := COLDEF FROM TABELTEMP WHERE TMPCODE = l_TMPCODE ;
   END;
ELSE
   BEGIN
     l_CREATED  := 0  ;    --TABLE TIDAK TERCREATE....DEFINISI KOLOM TIDAK ADA...
     RETURN;
   END;
END IF ;
l_SQLSTATE := '';
l_CREATED := 0 ;

EXECUTE 'CREATE TABLE ' || l_TMPCODE || l_TBLSTRUC ;
exception when SQLSTATE '00000' then 
begin 
   l_CREATED := 1 ;      --TABLE''S CREATED     
end ;
END ;
-- 
$BODY$
LANGUAGE 'plpgsql'
GO
