package solusi.hapis.backend.temp.model;
// Generated Apr 16, 2013 9:31:13 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * V14proj generated by hbm2java
 */
public class V14proj  implements java.io.Serializable {


     private String proj;
     private Integer version;
     private String projname;
     private Date startdate;
     private Date enddate;
     private Date tglsuspend;
     private String userid;
     private Date update;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;

    public V14proj() {
    }

	
    public V14proj(String proj) {
        this.proj = proj;
    }
    public V14proj(String proj, String projname, Date startdate, Date enddate, Date tglsuspend, String userid, Date update, String createdBy, Date createdOn, String updatedBy, Date updatedOn) {
       this.proj = proj;
       this.projname = projname;
       this.startdate = startdate;
       this.enddate = enddate;
       this.tglsuspend = tglsuspend;
       this.userid = userid;
       this.update = update;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
    }
   
    public String getProj() {
        return this.proj;
    }
    
    public void setProj(String proj) {
        this.proj = proj;
    }
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getProjname() {
        return this.projname;
    }
    
    public void setProjname(String projname) {
        this.projname = projname;
    }
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
    public Date getTglsuspend() {
        return this.tglsuspend;
    }
    
    public void setTglsuspend(Date tglsuspend) {
        this.tglsuspend = tglsuspend;
    }
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public Date getUpdate() {
        return this.update;
    }
    
    public void setUpdate(Date update) {
        this.update = update;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }




}


