package solusi.hapis.backend.temp.model;
// Generated Apr 16, 2013 9:31:13 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Ve1hdel generated by hbm2java
 */
public class Ve1hdel  implements java.io.Serializable {


     private int ve1Id;
     private Integer version;
     private String kdmodl;
     private String kdregs;
     private String rid;
     private String nip;
     private Date tanggal1;
     private String flgdppt;
     private String kddppt;
     private Date tanggal2;
     private String kode;
     private Short tahun;
     private Integer flagkel;
     private String nama;
     private Date upddate;
     private Date updtime;
     private String userid;
     private String keterangan;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;

    public Ve1hdel() {
    }

	
    public Ve1hdel(int ve1Id) {
        this.ve1Id = ve1Id;
    }
    public Ve1hdel(int ve1Id, String kdmodl, String kdregs, String rid, String nip, Date tanggal1, String flgdppt, String kddppt, Date tanggal2, String kode, Short tahun, Integer flagkel, String nama, Date upddate, Date updtime, String userid, String keterangan, String createdBy, Date createdOn, String updatedBy, Date updatedOn) {
       this.ve1Id = ve1Id;
       this.kdmodl = kdmodl;
       this.kdregs = kdregs;
       this.rid = rid;
       this.nip = nip;
       this.tanggal1 = tanggal1;
       this.flgdppt = flgdppt;
       this.kddppt = kddppt;
       this.tanggal2 = tanggal2;
       this.kode = kode;
       this.tahun = tahun;
       this.flagkel = flagkel;
       this.nama = nama;
       this.upddate = upddate;
       this.updtime = updtime;
       this.userid = userid;
       this.keterangan = keterangan;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
    }
   
    public int getVe1Id() {
        return this.ve1Id;
    }
    
    public void setVe1Id(int ve1Id) {
        this.ve1Id = ve1Id;
    }
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getKdmodl() {
        return this.kdmodl;
    }
    
    public void setKdmodl(String kdmodl) {
        this.kdmodl = kdmodl;
    }
    public String getKdregs() {
        return this.kdregs;
    }
    
    public void setKdregs(String kdregs) {
        this.kdregs = kdregs;
    }
    public String getRid() {
        return this.rid;
    }
    
    public void setRid(String rid) {
        this.rid = rid;
    }
    public String getNip() {
        return this.nip;
    }
    
    public void setNip(String nip) {
        this.nip = nip;
    }
    public Date getTanggal1() {
        return this.tanggal1;
    }
    
    public void setTanggal1(Date tanggal1) {
        this.tanggal1 = tanggal1;
    }
    public String getFlgdppt() {
        return this.flgdppt;
    }
    
    public void setFlgdppt(String flgdppt) {
        this.flgdppt = flgdppt;
    }
    public String getKddppt() {
        return this.kddppt;
    }
    
    public void setKddppt(String kddppt) {
        this.kddppt = kddppt;
    }
    public Date getTanggal2() {
        return this.tanggal2;
    }
    
    public void setTanggal2(Date tanggal2) {
        this.tanggal2 = tanggal2;
    }
    public String getKode() {
        return this.kode;
    }
    
    public void setKode(String kode) {
        this.kode = kode;
    }
    public Short getTahun() {
        return this.tahun;
    }
    
    public void setTahun(Short tahun) {
        this.tahun = tahun;
    }
    public Integer getFlagkel() {
        return this.flagkel;
    }
    
    public void setFlagkel(Integer flagkel) {
        this.flagkel = flagkel;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public Date getUpddate() {
        return this.upddate;
    }
    
    public void setUpddate(Date upddate) {
        this.upddate = upddate;
    }
    public Date getUpdtime() {
        return this.updtime;
    }
    
    public void setUpdtime(Date updtime) {
        this.updtime = updtime;
    }
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public String getKeterangan() {
        return this.keterangan;
    }
    
    public void setKeterangan(String keterangan) {
        this.keterangan = keterangan;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }




}


