package solusi.hapis.backend.temp.model;
// Generated Apr 16, 2013 9:31:13 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Z01ptgl generated by hbm2java
 */
public class Z01ptgl  implements java.io.Serializable {
	 private static final long serialVersionUID = 1L;
	 private int z01Id;
     private Integer version;
     private String journaltype;
     private String kdcabang;
     private String ketcabang;
     private String description;
     private Date applydate;
     private String document;
     private String accountcode;
     private String currency;
     private BigDecimal debit;
     private BigDecimal credit;
     private String description2;
     private Integer hold;
     private Integer intercompany;
     private Integer reversing;
     private Integer repeating;
     private Integer recurring;
     private Integer captureflg;
     private String userid;
     private Date upddate;
     private Date updtime;
     private String ws;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;
     
     private String tempCaptureFlg;
     
    public Z01ptgl() {
    }

	
    public Z01ptgl(int z01Id, String kdcabang, String document, String accountcode) {
        this.z01Id = z01Id;
        this.kdcabang = kdcabang;
        this.document = document;
        this.accountcode = accountcode;
    }
    public Z01ptgl(int z01Id, String journaltype, String kdcabang, String ketcabang, String description, Date applydate, String document, String accountcode, String currency, BigDecimal debit, BigDecimal credit, String description2, Integer hold, Integer intercompany, Integer reversing, Integer repeating, Integer recurring, Integer captureflg, String userid, Date upddate, Date updtime, String ws, String createdBy, Date createdOn, String updatedBy, Date updatedOn) {
       this.z01Id = z01Id;
       this.journaltype = journaltype;
       this.kdcabang = kdcabang;
       this.ketcabang = ketcabang;
       this.description = description;
       this.applydate = applydate;
       this.document = document;
       this.accountcode = accountcode;
       this.currency = currency;
       this.debit = debit;
       this.credit = credit;
       this.description2 = description2;
       this.hold = hold;
       this.intercompany = intercompany;
       this.reversing = reversing;
       this.repeating = repeating;
       this.recurring = recurring;
       this.captureflg = captureflg;
       this.userid = userid;
       this.upddate = upddate;
       this.updtime = updtime;
       this.ws = ws;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
    }
   
    public int getZ01Id() {
        return this.z01Id;
    }
    
    public void setZ01Id(int z01Id) {
        this.z01Id = z01Id;
    }
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getJournaltype() {
        return this.journaltype;
    }
    
    public void setJournaltype(String journaltype) {
        this.journaltype = journaltype;
    }
    public String getKdcabang() {
        return this.kdcabang;
    }
    
    public void setKdcabang(String kdcabang) {
        this.kdcabang = kdcabang;
    }
    public String getKetcabang() {
        return this.ketcabang;
    }
    
    public void setKetcabang(String ketcabang) {
        this.ketcabang = ketcabang;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getApplydate() {
        return this.applydate;
    }
    
    public void setApplydate(Date applydate) {
        this.applydate = applydate;
    }
    public String getDocument() {
        return this.document;
    }
    
    public void setDocument(String document) {
        this.document = document;
    }
    public String getAccountcode() {
        return this.accountcode;
    }
    
    public void setAccountcode(String accountcode) {
        this.accountcode = accountcode;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    public BigDecimal getDebit() {
        return this.debit;
    }
    
    public void setDebit(BigDecimal debit) {
        this.debit = debit;
    }
    public BigDecimal getCredit() {
        return this.credit;
    }
    
    public void setCredit(BigDecimal credit) {
        this.credit = credit;
    }
    public String getDescription2() {
        return this.description2;
    }
    
    public void setDescription2(String description2) {
        this.description2 = description2;
    }
    public Integer getHold() {
        return this.hold;
    }
    
    public void setHold(Integer hold) {
        this.hold = hold;
    }
    public Integer getIntercompany() {
        return this.intercompany;
    }
    
    public void setIntercompany(Integer intercompany) {
        this.intercompany = intercompany;
    }
    public Integer getReversing() {
        return this.reversing;
    }
    
    public void setReversing(Integer reversing) {
        this.reversing = reversing;
    }
    public Integer getRepeating() {
        return this.repeating;
    }
    
    public void setRepeating(Integer repeating) {
        this.repeating = repeating;
    }
    public Integer getRecurring() {
        return this.recurring;
    }
    
    public void setRecurring(Integer recurring) {
        this.recurring = recurring;
    }
    public Integer getCaptureflg() {
        return this.captureflg;
    }
    
    public void setCaptureflg(Integer captureflg) {
        this.captureflg = captureflg;
    }
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public Date getUpddate() {
        return this.upddate;
    }
    
    public void setUpddate(Date upddate) {
        this.upddate = upddate;
    }
    public Date getUpdtime() {
        return this.updtime;
    }
    
    public void setUpdtime(Date updtime) {
        this.updtime = updtime;
    }
    public String getWs() {
        return this.ws;
    }
    
    public void setWs(String ws) {
        this.ws = ws;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }
    
	public String getTempCaptureFlg() {
		return tempCaptureFlg;
	}
    
	public void setTempCaptureFlg(String tempCaptureFlg) {
		this.tempCaptureFlg = tempCaptureFlg;
	}
}