package solusi.hapis.backend.temp.model;
// Generated Apr 16, 2013 9:31:13 AM by Hibernate Tools 3.2.1.GA



/**
 * Z03ptglId generated by hbm2java
 */
public class Z03ptglId  implements java.io.Serializable {


     private String kdcabang;
     private String proyek;
     private String document;
     private String accountcode;

    public Z03ptglId() {
    }

    public Z03ptglId(String kdcabang, String proyek, String document, String accountcode) {
       this.kdcabang = kdcabang;
       this.proyek = proyek;
       this.document = document;
       this.accountcode = accountcode;
    }
   
    public String getKdcabang() {
        return this.kdcabang;
    }
    
    public void setKdcabang(String kdcabang) {
        this.kdcabang = kdcabang;
    }
    public String getProyek() {
        return this.proyek;
    }
    
    public void setProyek(String proyek) {
        this.proyek = proyek;
    }
    public String getDocument() {
        return this.document;
    }
    
    public void setDocument(String document) {
        this.document = document;
    }
    public String getAccountcode() {
        return this.accountcode;
    }
    
    public void setAccountcode(String accountcode) {
        this.accountcode = accountcode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Z03ptglId) ) return false;
		 Z03ptglId castOther = ( Z03ptglId ) other; 
         
		 return ( (this.getKdcabang()==castOther.getKdcabang()) || ( this.getKdcabang()!=null && castOther.getKdcabang()!=null && this.getKdcabang().equals(castOther.getKdcabang()) ) )
 && ( (this.getProyek()==castOther.getProyek()) || ( this.getProyek()!=null && castOther.getProyek()!=null && this.getProyek().equals(castOther.getProyek()) ) )
 && ( (this.getDocument()==castOther.getDocument()) || ( this.getDocument()!=null && castOther.getDocument()!=null && this.getDocument().equals(castOther.getDocument()) ) )
 && ( (this.getAccountcode()==castOther.getAccountcode()) || ( this.getAccountcode()!=null && castOther.getAccountcode()!=null && this.getAccountcode().equals(castOther.getAccountcode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getKdcabang() == null ? 0 : this.getKdcabang().hashCode() );
         result = 37 * result + ( getProyek() == null ? 0 : this.getProyek().hashCode() );
         result = 37 * result + ( getDocument() == null ? 0 : this.getDocument().hashCode() );
         result = 37 * result + ( getAccountcode() == null ? 0 : this.getAccountcode().hashCode() );
         return result;
   }   


}


