
CREATE TABLE APP_NEWS(
	ANW_ID serial,  
	ANW_TEXT varchar(1000) NULL,
	ANW_DATE date NOT NULL,
	VERSION int NOT NULL,
 CONSTRAINT pk_APP_NEWS PRIMARY KEY 
(
	ANW_id
) );


CREATE TABLE ARTIKEL(
	ART_ID serial,  
	ART_KURZBEZEICHNUNG varchar(50) NOT NULL,
	ART_LANGBEZEICHNUNG varchar(1000) NULL,
	ART_NR varchar(20) NOT NULL,
	ART_PREIS numeric(12, 2) NOT NULL,
	VERSION int NOT NULL,
 CONSTRAINT pk_ARTIKEL PRIMARY KEY 
(
	ART_id
) );




CREATE TABLE AUFTRAG(
	AUF_ID serial,  
	AUF_KUN_ID int NOT NULL,
	AUF_NR varchar(20) NOT NULL,
	AUF_BEZEICHNUNG varchar(50) NULL,
	VERSION int NOT NULL,
 CONSTRAINT pk_AUFTRAG PRIMARY KEY 
(
	AUF_id
)) ;


CREATE TABLE AUFTRAGPOSITION(
	AUP_ID serial,  
	AUP_AUF_ID int NOT NULL,
	ART_ID int NULL,
	AUP_POSITION int NULL,
	AUP_MENGE numeric(12, 2) NULL,
	AUP_EINZELWERT numeric(12, 2) NULL,
	AUP_GESAMTWERT numeric(12, 2) NULL,
	VERSION int NOT NULL,
 CONSTRAINT pk_AUFTRAGPOSITION PRIMARY KEY 
(
	AUP_id
)) ;


CREATE TABLE BRANCHE(
	BRA_ID serial,  
	BRA_NR varchar(20) NULL,
	BRA_BEZEICHNUNG varchar(30) NOT NULL,
	VERSION int NOT NULL,
 CONSTRAINT pk_BRANCHE PRIMARY KEY 
(
	BRA_id
) ); 

CREATE TABLE CALENDAR_EVENT(
	CLE_ID serial,  
	CLE_TITLE varchar(20) NULL,
	CLE_CONTENT varchar(300) NOT NULL,
	CLE_BEGIN_DATE timestamp(7) NOT NULL,
	CLE_END_DATE timestamp(7) NOT NULL,
	CLE_HEADER_COLOR varchar(10) NULL,
	CLE_CONTENT_COLOR varchar(10) NULL,
	CLE_USR_ID int NOT NULL,
	CLE_LOCKED smallint NULL,
	VERSION int NOT NULL,
 CONSTRAINT pk_CALENDAR_EVENT PRIMARY KEY 
(
	CLE_id
) ) ; 


CREATE TABLE FILIALE(
	FIL_ID serial,  
	FIL_NR varchar(20) NOT NULL,
	FIL_BEZEICHNUNG varchar(50) NULL,
	FIL_NAME1 varchar(50) NULL,
	FIL_NAME2 varchar(50) NULL,
	FIL_ORT varchar(50) NULL,
	VERSION int NOT NULL,
 CONSTRAINT pk_FILIALE PRIMARY KEY 
(
	FIL_id
)) ;


CREATE TABLE GUESTBOOK(
	GUB_ID serial,  
	GUB_SUBJECT varchar(40) NOT NULL,
	GUB_DATE timestamp(7) NOT NULL,
	GUB_USR_NAME varchar(40) NOT NULL,
	GUB_TEXT varchar(1000) NULL,
	VERSION int NULL,
 CONSTRAINT pk_GUESTBOOK PRIMARY KEY 
(
	GUB_id
) ); 


CREATE TABLE HIBERNATE_ENTITY_STATISTICS(
	ID serial,  
	HIBERNATEENTITYSTATISTICSID bigint NOT NULL,
	ENTITYNAME varchar(1000) NOT NULL,
	LOADCOUNT int NOT NULL,
	UPDATECOUNT int NOT NULL,
	INSERTCOUNT int NOT NULL,
	DELETECOUNT int NOT NULL,
	FETCHCOUNT int NOT NULL,
	OPTIMISTICFAILURECOUNT int NOT NULL,
 CONSTRAINT HIBERNATEENTITYSTATISTICS_PKEY PRIMARY KEY 
(
	ID 
) ); 


CREATE TABLE HIBERNATE_STATISTICS(
	ID serial,  
	FLUSHCOUNT int NOT NULL,
	PREPARESTATEMENTCOUNT int NOT NULL,
	ENTITYLOADCOUNT int NOT NULL,
	ENTITYUPDATECOUNT int NOT NULL,
	ENTITYINSERTCOUNT int NOT NULL,
	ENTITYDELETECOUNT int NOT NULL,
	ENTITYFETCHCOUNT int NOT NULL,
	COLLECTIONLOADCOUNT int NOT NULL,
	COLLECTIONUPDATECOUNT int NOT NULL,
	COLLECTIONREMOVECOUNT int NOT NULL,
	COLLECTIONRECREATECOUNT int NOT NULL,
	COLLECTIONFETCHCOUNT int NOT NULL,
	QUERYEXECUTIONCOUNT int NOT NULL,
	QUERYEXECUTIONMAXTIME int NOT NULL,
	OPTIMISTICFAILURECOUNT int NOT NULL,
	QUERYEXECUTIONMAXTIMEQUERYSTRING varchar(1000) NULL,
	CALLMETHOD varchar(1000) NOT NULL,
	JAVAFINISHMS bigint NOT NULL,
	FINISHTIME timestamp(7) NOT NULL,
 CONSTRAINT HIBERNATESTATISTICS_PKEY PRIMARY KEY 
(
	ID 
)); 

CREATE TABLE IPC_IP2COUNTRY(
	IPC_ID serial,  
	IPC_IP_FROM int NULL,
	IPC_IP_TO int NULL,
	IPC_COUNTRY_CODE2 varchar(2) NULL,
	IPC_COUNTRY_CODE3 varchar(3) NULL,
	IPC_COUNTRY_NAME varchar(50) NULL,
	VERSION int NOT NULL,
 CONSTRAINT pk_IPC_IP2COUNTRY PRIMARY KEY 
(
	IPC_id
));

CREATE TABLE KUNDE(
	KUN_ID serial,  
	KUN_FIL_ID int NOT NULL,
	KUN_BRA_ID int NULL,
	KUN_NR varchar(20) NOT NULL,
	KUN_MATCHCODE varchar(20) NULL,
	KUN_NAME1 varchar(50) NULL,
	KUN_NAME2 varchar(50) NULL,
	KUN_ORT varchar(50) NULL,
	KUN_MAHNSPERRE smallint NULL,
	VERSION int NOT NULL,
 CONSTRAINT pk_KUNDE PRIMARY KEY 
(
	KUN_id
));

CREATE TABLE LOG_IP2COUNTRY(
	I2C_ID serial,  
	CCD_ID int NULL,
	I2C_CITY varchar(50) NULL,
	I2C_LATITUDE decimal(18, 0) NULL,
	I2C_LONGITUDE decimal(18, 0) NULL,
	VERSION int NULL,
 CONSTRAINT pk_LOG_IP2COUNTRY PRIMARY KEY 
(
	I2C_id
) );



CREATE TABLE SEC_GROUP(
	GRP_ID int NOT NULL,
	GRP_SHORTDESCRIPTION varchar(60) NULL,
	GRP_LONGDESCRIPTION varchar(1000) NULL,
	VERSION int NOT NULL,
	MODUL varchar(20) NULL,
 CONSTRAINT pk_SEC_GROUP PRIMARY KEY 
(
	GRP_id
)); 

CREATE TABLE SEC_GROUPRIGHT(
	GRI_ID serial,  
	GRP_ID int NOT NULL,
	RIG_ID int NOT NULL,
	VERSION int NOT NULL,
 CONSTRAINT pk_SEC_GROUPRIGHT PRIMARY KEY 
(
	GRI_id
) ); 

CREATE TABLE SEC_LOGINLOG(
	LGL_ID serial,  
	I2C_ID int NULL,
	LGL_LOGINNAME varchar(50) NOT NULL,
	LGL_LOGTIME timestamp(7) NOT NULL,
	LGL_IP varchar(19) NULL,
	LGL_BROWSERTYPE varchar(40) NULL,
	LGL_STATUS_ID int NOT NULL,
	LGL_SESSIONID varchar(50) NULL,
	VERSION int NOT NULL,
 CONSTRAINT pk_SEC_LOGINLOG PRIMARY KEY 
(
	LGL_id
) ); 


CREATE TABLE SEC_RIGHT(
	RIG_ID int NOT NULL,
	RIG_TYPE int NULL,
	RIG_NAME varchar(50) NOT NULL,
	VERSION int NOT NULL,
 CONSTRAINT pk_SEC_RIGHT PRIMARY KEY 
(
	RIG_id
) ); 


CREATE TABLE SEC_ROLE(
	ROL_ID serial,  
	ROL_SHORTDESCRIPTION varchar(30) NOT NULL,
	ROL_LONGDESCRIPTION varchar(1000) NULL,
	VERSION int NOT NULL,
 CONSTRAINT pk_SEC_ROLE PRIMARY KEY 
(
	ROL_id
) ); 

CREATE TABLE SEC_ROLEGROUP(
	RLG_ID serial,  
	GRP_ID int NOT NULL,
	ROL_ID int NOT NULL,
	VERSION int NOT NULL,
 CONSTRAINT pk_SEC_ROLEGROUP PRIMARY KEY 
(
	RLG_id
) ); 

CREATE TABLE SEC_USER(
	USR_ID serial,  
	USR_LOGINNAME varchar(50) NOT NULL,
	USR_PASSWORD varchar(50) NOT NULL,
	USR_LASTNAME varchar(50) NULL,
	USR_FIRSTNAME varchar(50) NULL,
	USR_EMAIL varchar(200) NULL,
	USR_LOCALE varchar(5) NULL,
	USR_ENABLED smallint NOT NULL,
	USR_ACCOUNTNONEXPIRED smallint NOT NULL,
	USR_CREDENTIALSNONEXPIRED smallint NOT NULL,
	USR_ACCOUNTNONLOCKED smallint NOT NULL,
	USR_TOKEN varchar(20) NULL,
	VERSION int NOT NULL,
	NIK_ID int NULL,
	SUBUNIT_ID int NULL,
	CREATED_ON timestamp(7) NULL,
	CREATED_BY varchar(50) NULL,
	UPDATED_ON timestamp(7) NULL,
	UPDATED_BY varchar(50) NULL,
 CONSTRAINT pk_SEC_USER PRIMARY KEY 
(
	USR_id
) ); 

CREATE TABLE SEC_USERROLE(
	URR_ID serial,  
	USR_ID int NOT NULL,
	ROL_ID int NOT NULL,
	VERSION int NOT NULL,
 CONSTRAINT pk_SEC_USERROLE PRIMARY KEY 
(
	URR_id
) ); 

CREATE TABLE SYS_COUNTRYCODE(
	CCD_ID serial,  
	CCD_NAME varchar(48) NULL,
	CCD_CODE2 varchar(2) NOT NULL,
	VERSION int NULL,
 CONSTRAINT pk_SYS_COUNTRYCODE PRIMARY KEY 
(
	CCD_id
));


CREATE TABLE SYS_IP4COUNTRY(
	I4CO_ID serial,  
	I4CO_IP int NULL,
	I4CO_CCD_ID int NULL,
	VERSION int NULL,
 CONSTRAINT pk_SYS_IP4COUNTRY PRIMARY KEY 
(
	I4CO_id
) ); 



ALTER TABLE APP_NEWS ALTER COLUMN VERSION SET DEFAULT 0 ;  


ALTER TABLE ARTIKEL ALTER COLUMN ART_PREIS SET DEFAULT 0.00 ;  


ALTER TABLE ARTIKEL ALTER COLUMN VERSION SET DEFAULT 0 ;  


ALTER TABLE AUFTRAG ALTER COLUMN VERSION SET DEFAULT 0 ;  


ALTER TABLE AUFTRAGPOSITION ALTER COLUMN VERSION SET DEFAULT 0 ;  


ALTER TABLE BRANCHE ALTER COLUMN VERSION SET DEFAULT 0 ;  


ALTER TABLE CALENDAR_EVENT ALTER COLUMN CLE_LOCKED SET DEFAULT 0 ;  


ALTER TABLE CALENDAR_EVENT ALTER COLUMN VERSION SET DEFAULT 0 ;  


ALTER TABLE FILIALE ALTER COLUMN VERSION SET DEFAULT 0 ;  


ALTER TABLE IPC_IP2COUNTRY ALTER COLUMN VERSION SET DEFAULT 0 ;  


ALTER TABLE KUNDE ALTER COLUMN VERSION SET DEFAULT 0 ;  


ALTER TABLE LOG_IP2COUNTRY ALTER COLUMN VERSION SET DEFAULT 0 ;  


ALTER TABLE SEC_GROUP ALTER COLUMN VERSION SET DEFAULT 0 ;  


ALTER TABLE SEC_GROUPRIGHT ALTER COLUMN VERSION SET DEFAULT 0 ;  


ALTER TABLE SEC_LOGINLOG ALTER COLUMN VERSION SET DEFAULT 0 ;  


ALTER TABLE SEC_RIGHT ALTER COLUMN RIG_TYPE SET DEFAULT 1 ;  


ALTER TABLE SEC_RIGHT ALTER COLUMN VERSION SET DEFAULT 0 ;  


ALTER TABLE SEC_ROLE ALTER COLUMN VERSION SET DEFAULT 0 ;  


ALTER TABLE SEC_ROLEGROUP ALTER COLUMN VERSION SET DEFAULT 0 ;  


ALTER TABLE SEC_USER ALTER COLUMN USR_ENABLED SET DEFAULT 0 ;  


ALTER TABLE SEC_USER ALTER COLUMN USR_ACCOUNTNONEXPIRED SET DEFAULT 1 ;  


ALTER TABLE SEC_USER ALTER COLUMN USR_CREDENTIALSNONEXPIRED SET DEFAULT 1 ;  


ALTER TABLE SEC_USER ALTER COLUMN USR_ACCOUNTNONLOCKED SET DEFAULT 1 ;  


ALTER TABLE SEC_USER ALTER COLUMN VERSION SET DEFAULT 0 ;  


ALTER TABLE SEC_USERROLE ALTER COLUMN VERSION SET DEFAULT 0 ;  


ALTER TABLE SYS_COUNTRYCODE ALTER COLUMN VERSION SET DEFAULT 0 ;  


ALTER TABLE SYS_IP4COUNTRY ALTER COLUMN VERSION SET DEFAULT 0 ;  