package solusi.hapis.backend.model;
// Generated 06 Mar 12 10:03:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Auftrag generated by hbm2java
 */
public class Auftrag implements java.io.Serializable {


    private int aufId;
    private int version;
    private Kunde kunde;
    private String aufNr;
    private String aufBezeichnung;
    private Set<Auftragposition> auftragpositions = new HashSet<Auftragposition>(0);

    public Auftrag() {
    }


    public Auftrag(int aufId, Kunde kunde, String aufNr) {
        this.aufId = aufId;
        this.kunde = kunde;
        this.aufNr = aufNr;
    }

    public Auftrag(int aufId, Kunde kunde, String aufNr, String aufBezeichnung, Set<Auftragposition> auftragpositions) {
        this.aufId = aufId;
        this.kunde = kunde;
        this.aufNr = aufNr;
        this.aufBezeichnung = aufBezeichnung;
        this.auftragpositions = auftragpositions;
    }

    public int getAufId() {
        return this.aufId;
    }

    public void setAufId(int aufId) {
        this.aufId = aufId;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public Kunde getKunde() {
        return this.kunde;
    }

    public void setKunde(Kunde kunde) {
        this.kunde = kunde;
    }

    public String getAufNr() {
        return this.aufNr;
    }

    public void setAufNr(String aufNr) {
        this.aufNr = aufNr;
    }

    public String getAufBezeichnung() {
        return this.aufBezeichnung;
    }

    public void setAufBezeichnung(String aufBezeichnung) {
        this.aufBezeichnung = aufBezeichnung;
    }

    public Set<Auftragposition> getAuftragpositions() {
        return this.auftragpositions;
    }

    public void setAuftragpositions(Set<Auftragposition> auftragpositions) {
        this.auftragpositions = auftragpositions;
    }


}


