package solusi.hapis.backend.model;
// Generated 06 Mar 12 10:03:27 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Auftragposition generated by hbm2java
 */
public class Auftragposition implements java.io.Serializable {


    private int aupId;
    private int version;
    private Auftrag auftrag;
//    private Artikel artikel;
    private Integer aupPosition;
    private BigDecimal aupMenge;
    private BigDecimal aupEinzelwert;
    private BigDecimal aupGesamtwert;

    public Auftragposition() {
    }


    public Auftragposition(int aupId, Auftrag auftrag) {
        this.aupId = aupId;
        this.auftrag = auftrag;
    }

    public Auftragposition(int aupId, Auftrag auftrag, Integer aupPosition, BigDecimal aupMenge, BigDecimal aupEinzelwert, BigDecimal aupGesamtwert) {
        this.aupId = aupId;
        this.auftrag = auftrag;
        this.aupPosition = aupPosition;
        this.aupMenge = aupMenge;
        this.aupEinzelwert = aupEinzelwert;
        this.aupGesamtwert = aupGesamtwert;
    }

    public int getAupId() {
        return this.aupId;
    }

    public void setAupId(int aupId) {
        this.aupId = aupId;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public Auftrag getAuftrag() {
        return this.auftrag;
    }

    public void setAuftrag(Auftrag auftrag) {
        this.auftrag = auftrag;
    }


    public Integer getAupPosition() {
        return this.aupPosition;
    }

    public void setAupPosition(Integer aupPosition) {
        this.aupPosition = aupPosition;
    }

    public BigDecimal getAupMenge() {
        return this.aupMenge;
    }

    public void setAupMenge(BigDecimal aupMenge) {
        this.aupMenge = aupMenge;
    }

    public BigDecimal getAupEinzelwert() {
        return this.aupEinzelwert;
    }

    public void setAupEinzelwert(BigDecimal aupEinzelwert) {
        this.aupEinzelwert = aupEinzelwert;
    }

    public BigDecimal getAupGesamtwert() {
        return this.aupGesamtwert;
    }

    public void setAupGesamtwert(BigDecimal aupGesamtwert) {
        this.aupGesamtwert = aupGesamtwert;
    }


}


