package solusi.hapis.backend.model;
// Generated 06 Mar 12 10:03:27 by Hibernate Tools 3.2.1.GA


/**
 * IpcIp2country generated by hbm2java
 */
public class IpcIp2country implements java.io.Serializable {


    private int ipcId;
    private int version;
    private Integer ipcIpFrom;
    private Integer ipcIpTo;
    private String ipcCountryCode2;
    private String ipcCountryCode3;
    private String ipcCountryName;

    public IpcIp2country() {
    }


    public IpcIp2country(int ipcId) {
        this.ipcId = ipcId;
    }

    public IpcIp2country(int ipcId, Integer ipcIpFrom, Integer ipcIpTo, String ipcCountryCode2, String ipcCountryCode3, String ipcCountryName) {
        this.ipcId = ipcId;
        this.ipcIpFrom = ipcIpFrom;
        this.ipcIpTo = ipcIpTo;
        this.ipcCountryCode2 = ipcCountryCode2;
        this.ipcCountryCode3 = ipcCountryCode3;
        this.ipcCountryName = ipcCountryName;
    }

    public int getIpcId() {
        return this.ipcId;
    }

    public void setIpcId(int ipcId) {
        this.ipcId = ipcId;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public Integer getIpcIpFrom() {
        return this.ipcIpFrom;
    }

    public void setIpcIpFrom(Integer ipcIpFrom) {
        this.ipcIpFrom = ipcIpFrom;
    }

    public Integer getIpcIpTo() {
        return this.ipcIpTo;
    }

    public void setIpcIpTo(Integer ipcIpTo) {
        this.ipcIpTo = ipcIpTo;
    }

    public String getIpcCountryCode2() {
        return this.ipcCountryCode2;
    }

    public void setIpcCountryCode2(String ipcCountryCode2) {
        this.ipcCountryCode2 = ipcCountryCode2;
    }

    public String getIpcCountryCode3() {
        return this.ipcCountryCode3;
    }

    public void setIpcCountryCode3(String ipcCountryCode3) {
        this.ipcCountryCode3 = ipcCountryCode3;
    }

    public String getIpcCountryName() {
        return this.ipcCountryName;
    }

    public void setIpcCountryName(String ipcCountryName) {
        this.ipcCountryName = ipcCountryName;
    }


}


