package solusi.hapis.backend.model;
// Generated 06 Mar 12 10:03:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * LogIp2country generated by hbm2java
 */
public class LogIp2country implements java.io.Serializable {


    private int i2cId;
    private Integer version;
    private SysCountrycode sysCountrycode;
    private String i2cCity;
    private Integer i2cLatitude;
    private Integer i2cLongitude;
    private Set<SecLoginlog> secLoginlogs = new HashSet<SecLoginlog>(0);

    public LogIp2country() {
    }


    public LogIp2country(int i2cId) {
        this.i2cId = i2cId;
    }

    public LogIp2country(int i2cId, SysCountrycode sysCountrycode, String i2cCity, Integer i2cLatitude, Integer i2cLongitude, Set<SecLoginlog> secLoginlogs) {
        this.i2cId = i2cId;
        this.sysCountrycode = sysCountrycode;
        this.i2cCity = i2cCity;
        this.i2cLatitude = i2cLatitude;
        this.i2cLongitude = i2cLongitude;
        this.secLoginlogs = secLoginlogs;
    }

    public int getI2cId() {
        return this.i2cId;
    }

    public void setI2cId(int i2cId) {
        this.i2cId = i2cId;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public SysCountrycode getSysCountrycode() {
        return this.sysCountrycode;
    }

    public void setSysCountrycode(SysCountrycode sysCountrycode) {
        this.sysCountrycode = sysCountrycode;
    }

    public String getI2cCity() {
        return this.i2cCity;
    }

    public void setI2cCity(String i2cCity) {
        this.i2cCity = i2cCity;
    }

    public Integer getI2cLatitude() {
        return this.i2cLatitude;
    }

    public void setI2cLatitude(Integer i2cLatitude) {
        this.i2cLatitude = i2cLatitude;
    }

    public Integer getI2cLongitude() {
        return this.i2cLongitude;
    }

    public void setI2cLongitude(Integer i2cLongitude) {
        this.i2cLongitude = i2cLongitude;
    }

    public Set<SecLoginlog> getSecLoginlogs() {
        return this.secLoginlogs;
    }

    public void setSecLoginlogs(Set<SecLoginlog> secLoginlogs) {
        this.secLoginlogs = secLoginlogs;
    }


}


