package solusi.hapis.backend.model;
// Generated 06 Mar 12 10:03:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SysCountrycode generated by hbm2java
 */
public class SysCountrycode implements java.io.Serializable {


    private int ccdId;
    private Integer version;
    private String ccdName;
    private String ccdCode2;
    private Set<LogIp2country> logIp2countries = new HashSet<LogIp2country>(0);

    public SysCountrycode() {
    }


    public SysCountrycode(int ccdId, String ccdCode2) {
        this.ccdId = ccdId;
        this.ccdCode2 = ccdCode2;
    }

    public SysCountrycode(int ccdId, String ccdName, String ccdCode2, Set<LogIp2country> logIp2countries) {
        this.ccdId = ccdId;
        this.ccdName = ccdName;
        this.ccdCode2 = ccdCode2;
        this.logIp2countries = logIp2countries;
    }

    public int getCcdId() {
        return this.ccdId;
    }

    public void setCcdId(int ccdId) {
        this.ccdId = ccdId;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getCcdName() {
        return this.ccdName;
    }

    public void setCcdName(String ccdName) {
        this.ccdName = ccdName;
    }

    public String getCcdCode2() {
        return this.ccdCode2;
    }

    public void setCcdCode2(String ccdCode2) {
        this.ccdCode2 = ccdCode2;
    }

    public Set<LogIp2country> getLogIp2countries() {
        return this.logIp2countries;
    }

    public void setLogIp2countries(Set<LogIp2country> logIp2countries) {
        this.logIp2countries = logIp2countries;
    }


}


