package solusi.hapis.backend.model;
// Generated 06 Mar 12 10:03:27 by Hibernate Tools 3.2.1.GA


/**
 * SysIp4country generated by hbm2java
 */
public class SysIp4country implements java.io.Serializable {


    private int i4coId;
    private Integer version;
    private Integer i4coIp;
    private Integer i4coCcdId;

    public SysIp4country() {
    }


    public SysIp4country(int i4coId) {
        this.i4coId = i4coId;
    }

    public SysIp4country(int i4coId, Integer i4coIp, Integer i4coCcdId) {
        this.i4coId = i4coId;
        this.i4coIp = i4coIp;
        this.i4coCcdId = i4coCcdId;
    }

    public int getI4coId() {
        return this.i4coId;
    }

    public void setI4coId(int i4coId) {
        this.i4coId = i4coId;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Integer getI4coIp() {
        return this.i4coIp;
    }

    public void setI4coIp(Integer i4coIp) {
        this.i4coIp = i4coIp;
    }

    public Integer getI4coCcdId() {
        return this.i4coCcdId;
    }

    public void setI4coCcdId(Integer i4coCcdId) {
        this.i4coCcdId = i4coCcdId;
    }


}


