CREATE OR REPLACE FUNCTION FN_CARIRANGESEC (l_RID	VARCHAR(1), 
					    l_NIP      	VARCHAR(10),
					    l_Periode  	DATE)

RETURNS VARCHAR(4) 

AS $$ 
-----
DECLARE l_TGL DATE; l_CABA VARCHAR(4); l_GLNG VARCHAR(4); l_BALIKAN VARCHAR(4) ;

BEGIN
	SELECT MAX(S05.TGLPOSTING) 
	INTO l_TGL 
	FROM S05PSTD S05
	WHERE S05.NIP = l_NIP ; --AND TGLPOSTING <=l_PERIODE 

	SELECT S01.KDCABA,  S01.KDGLNG 
	INTO l_CABA, l_GLNG 
	FROM S01HGAJ S01
	WHERE S01.NIP = l_NIP AND S01.TGLPAYR = l_TGL ;

IF l_RID ='C' THEN 
   l_BALIKAN := l_CABA ;
ELSE 
   l_BALIKAN := l_GLNG ;
END IF ; 
RETURN l_BALIKAN ;
END ; 

$$ language 'plpgsql' ;  

---
/*
SELECT FN_CARIRANGESEC('C','200211018', '2009-12-31' )
SELECT * FROM S01HGAJ WHERE NIP = '200211018' 
*/
